### ISSUE TITLE
Decrease peak memory usage when getting value of single JSON element

### ISSUE THREAD

**Issue by MurzNN** [pcrov/JsonReader#24]
Thanks for so useful library to operate with large JSON objects in PHP! But I have a problem with large peak memory usage when using `value()` function.
For example, if I try to get value of one inner JSON element (array item) with length of 4,2 megabytes, peak memory usage is 257 megabytes, so more than 60 times larger than actual JSON data! 

Can you recommend some ways to decrease peak memory usage with your library?

**Comment by MurzNN** [comment]
Here is example of Overpass API reply, that contains boundary polygons of first 3 countries: https://gist.github.com/MurzNN/f4b0aa849da062b1e6cc473bed1f3f0e
It have size 8,4 megabytes with array in `members` key, containing 3 elements.

So I use your JsonReader to read those items sequentially and got the memory limit problems on systems with 128MB memory limits.

**Comment by MurzNN** [comment]
Here is the code to reproduce this problem:
```php
use pcrov\JsonReader\JsonReader;

$reader = new JsonReader();
$reader->open("overpass_countries_geom_3.json");

$reader->read("elements");
$reader->read();

$i = 1;
do {
  $value = $reader->value();
  echo "Reading array item $i - memory usage " . round(memory_get_usage() / 1024 / 1024, 2) . ' mb, peak ' . round(memory_get_peak_usage() / 1024 / 1024, 2) . ' mb' . PHP_EOL;
  echo "JSON length: " . round(strlen(json_encode($value)) / 1024 / 1024, 2) . ' mb' . PHP_EOL;
  $nextItem = $reader->next();
  $i++;
} while ($nextItem !== FALSE);

$reader->close();
```
And it's output:
```
Reading array item 1 - memory usage 3.3 mb, peak 3.31 mb
JSON length: 0.06 mb
Reading array item 2 - memory usage 96.18 mb, peak 96.84 mb
JSON length: 1.44 mb
Reading array item 3 - memory usage 249.81 mb, peak 271.01 mb
JSON length: 4 mb
Reading array item 4 - memory usage 0.38 mb, peak 271.01 mb
JSON length: 0 mb
Reading array item 5 - memory usage 0.38 mb, peak 271.01 mb
JSON length: 0 mb
```

Even if we comment out the string with `json_encode` (to remove potential memory usage source), values are still the same!

**Comment by pcrov** [comment]
Thank you for the report, sample data, and test script!

What you're seeing here is `value` not being super space efficient when it comes to operating on largish arrays and objects. This is because the tree builder caches nodes so that the cursor doesn't prematurely advance. The idea being the reader's position should only advance when told to by `read` or `next`. 

For best results I usually recommend drilling down to work on smaller chunks at a time, e.g. individual `"members"` entries, if possible. I know this isn't always convenient but on the upside resource use is not only way lower but typically more predictable.

That said I'll have a look at making the reader more mindful of this use pattern. I'd be surprised if we couldn't at least bring that cache size down some.

**Comment by MurzNN** [comment]
Thanks, I hope you will find ways to optimize this! Drilling down is not too easy, especially for complex structures.
Also maybe as alternative you can provide something like `$reader->rawValue()` method that will return string with plain text of current element, without deep parsing of data?

**Comment by pcrov** [comment]
Flattening the cache cut its memory use about in half. Not quite what you're hoping for but not too shabby. To temper the point of comparison a bit I think it's more reasonable to look at the memory footprint of the `$value` you're getting (or at least a close approximation) rather than the string length of it serialized as JSON. For item 3 this is 49.08 mb despite serializing down to 4 mb.

So new script:

```php
use pcrov\JsonReader\JsonReader;
$reader = new JsonReader();
$reader->open("overpass_countries_geom_3.json");

$reader->read("elements");
$reader->read();

$i = 1;
do {
  $value = $reader->value();
  echo "Reading array item $i - memory usage " . round(memory_get_usage() / 1024 / 1024, 2) . ' mb, peak ' . round(memory_get_peak_usage() / 1024 / 1024, 2) . ' mb' . PHP_EOL;
  echo "JSON length: " . round(strlen(json_encode($value)) / 1024 / 1024, 2) . ' mb' . PHP_EOL;
  echo 'Size of $value ', round(sizeofvar($value) / 1024 / 1024, 2), ' mb', PHP_EOL;
  $nextItem = $reader->next();
  $i++;
} while ($nextItem !== FALSE);

$reader->close();

// lifted from https://stackoverflow.com/a/2192689
function sizeofvar($var) {
    $start_memory = memory_get_usage();
    $tmp = unserialize(serialize($var));
    return memory_get_usage() - $start_memory;
}
```

Right now the output for this is:

```
Reading array item 1 - memory usage 4.04 mb, peak 4.05 mb
JSON length: 0.06 mb
Size of $value 0.66 mb
Reading array item 2 - memory usage 99.02 mb, peak 99.67 mb
JSON length: 1.44 mb
Size of $value 18.5 mb
Reading array item 3 - memory usage 252.65 mb, peak 273.85 mb
JSON length: 4 mb
Size of $value 49.08 mb
Reading array item 4 - memory usage 1.22 mb, peak 320.52 mb
JSON length: 0 mb
Size of $value 0 mb
Reading array item 5 - memory usage 1.22 mb, peak 320.52 mb
JSON length: 0 mb
Size of $value 0 mb
```

While for the `memory` branch:

```
Reading array item 1 - memory usage 2.87 mb, peak 2.89 mb
JSON length: 0.06 mb
Size of $value 0.66 mb
Reading array item 2 - memory usage 59.7 mb, peak 60.36 mb
JSON length: 1.44 mb
Size of $value 18.5 mb
Reading array item 3 - memory usage 132.11 mb, peak 153.32 mb
JSON length: 4 mb
Size of $value 49.08 mb
Reading array item 4 - memory usage 1.22 mb, peak 199.98 mb
JSON length: 0 mb
Size of $value 0 mb
Reading array item 5 - memory usage 1.22 mb, peak 199.98 mb
JSON length: 0 mb
Size of $value 0 mb
```

So peak use on item 3 drops from 273.85 mb to 153.32 mb to create a 49.08 mb value. Considering peak use includes that 49.08 mb too, along with what's basically an annotated copy of it in the form of nodes from the parser, there's only so low it'll go.

For a `rawValue` method provided by the reader I'd want to pass through source string data rather than reserialize, which would only increase memory use. The caching is a consequence of navigating with reader semantics while also working with non-seekable or rewindable inputs and providing access to fully built compound values at all. How that compound value is returned isn't so important.

However a `rawValue` function *using* the reader wouldn't be difficult. Navigate to the value you want and build the JSON string node by node while only pulling the value of scalars and stop when you've returned to the depth you started.

**Comment by MurzNN** [comment]
Thank you for you investigations! I've very surprised that size of that PHP array consumes 10 times more memory, than JSON string representation of it! Especially with a lot of float values, that in JSON are represented as string, but in PHP - as binary format.

**Comment by MurzNN** [comment]
Maybe also try object format of data, like in `json_decode` with default parameters? Seems objects can consume less memory, than associative arrays, regarding to this: https://gist.github.com/nikic/5015323

**Comment by pcrov** [comment]
Objects won't really help here. What nikic is talking about there hinges on this bit:

> The key here is that objects usually have a predefined set of keys, whereas arrays don't

That predefined set of keys are the properties of a class. We don't have that for the returned structures.

**Comment by MurzNN** [comment]
Hmm, peak usage for `json_decode` of separate file with item 4 content is 120.32 mb, comparing with 199.98 mb using custom decoding. So maybe the way with extracting substring and parsing it using `json_decode` will be easier than custom decoding process?

**Comment by pcrov** [comment]
For the reader to pass through source substrings it would only increase memory use, while returning re-json-encoded strings wouldn't lower it as the children of compound values would still need to be cached to preserve the reader's navigation semantics.

To meet your needs this would be something you build *using* the reader, not something provided by it. However you'd basically be creating a tree builder with additional re- encode/decode steps in the middle. I recommend skipping those and build your needed data structures directly.

**Comment by pcrov** [comment]
Just cut a new [release](https://github.com/pcrov/JsonReader/releases) including the memory use improvements I mentioned earlier. Not all you were hoping for but it's a big improvement.
